language: python
os:
  - linux
python:
  - 3.6
install:
  - pip install -r REQUIRE
before_script:
  - pip install flake8
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics